project12/app1/urls.py
from django.urls import path
from app1.views import *
app_name='chinnodu'

urlpatterns=[
    path('a1_first/',a1_first,name='a1_first')
]

project12/app2/urls.py
from django.urls import path
from app2.views import *
app_name='NS'

urlpatterns=[
    path('a2_first/',a2_first,name='a2_first')
]

project12/project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

project12/app1/models.py
from django.db import models

# Create your models here.

project12/app2/models.py
from django.db import models

# Create your models here.

project12/app1/views.py
from django.shortcuts import render

# Create your views here.
def a1_first(request):
    return render(request,'a1_first.html')

project12/app2/views.py
from django.shortcuts import render

# Create your views here.
def a2_first(request):
    return render(request,'a2_first.html')

project12/templates/a1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>iam Naven</h1>
        <a href="{% url 'NS:a2_first' %}">click go to Ns</a>
    </center>
</body>
</html>

project12/templates/a2_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Iam Ns</h1>
        <a href="{% url 'chinnodu:a1_first' %}">click go to Naveen</a>
    </center>
</body>
</html>